export const statesUSA = [
  { value: "AK", text: "Alaska" },
  { value: "AL", text: "Alabama" },
  { value: "AR", text: "Arkansas" },
  { value: "AS", text: "American Samoa" },
  { value: "AZ", text: "Arizona" },
  { value: "CA", text: "California" },
  { value: "CO", text: "Colorado" },
  { value: "CT", text: "Connecticut" },
  { value: "DC", text: "District of Columbia" },
  { value: "DE", text: "Delaware" },
  { value: "FL", text: "Florida" },
  { value: "GA", text: "Georgia" },
  { value: "GU", text: "Guam" },
  { value: "HI", text: "Hawaii" },
  { value: "IA", text: "Iowa" },
  { value: "ID", text: "Idaho" },
  { value: "IL", text: "Illinois" },
  { value: "IN", text: "Indiana" },
  { value: "KS", text: "Kansas" },
  { value: "KY", text: "Kentucky" },
  { value: "LA", text: "Louisiana" },
  { value: "MA", text: "Massachusetts" },
  { value: "MD", text: "Maryland" },
  { value: "ME", text: "Maine" },
  { value: "MI", text: "Michigan" },
  { value: "MN", text: "Minnesota" },
  { value: "MO", text: "Missouri" },
  { value: "MS", text: "Mississippi" },
  { value: "MT", text: "Montana" },
  { value: "NC", text: "North Carolina" },
  { value: "ND", text: "North Dakota" },
  { value: "NE", text: "Nebraska" },
  { value: "NH", text: "New Hampshire" },
  { value: "NJ", text: "New Jersey" },
  { value: "NM", text: "New Mexico" },
  { value: "NV", text: "Nevada" },
  { value: "NY", text: "New York" },
  { value: "OH", text: "Ohio" },
  { value: "OK", text: "Oklahoma" },
  { value: "OR", text: "Oregon" },
  { value: "PA", text: "Pennsylvania" },
  { value: "PR", text: "Puerto Rico" },
  { value: "RI", text: "Rhode Island" },
  { value: "SC", text: "South Carolina" },
  { value: "SD", text: "South Dakota" },
  { value: "TN", text: "Tennessee" },
  { value: "TX", text: "Texas" },
  { value: "UT", text: "Utah" },
  { value: "VA", text: "Virginia" },
  { value: "VI", text: "Virgin Islands" },
  { value: "VT", text: "Vermont" },
  { value: "WA", text: "Washington" },
  { value: "WI", text: "Wisconsin" },
  { value: "WV", text: "West Virginia" },
  { value: "WY", text: "Wyoming" },
];

export const departments = [
  { value: "sales", text: "Sales" },
  { value: "engineering", text: "Engineering" },
  { value: "hr", text: "Human Resources" },
  { value: "legal", text: "Legal" },
];

export const months = [
  { value: "0", text: "January" },
  { value: "1", text: "February" },
  { value: "2", text: "March" },
  { value: "3", text: "April" },
  { value: "4", text: "May" },
  { value: "5", text: "June" },
  { value: "6", text: "July" },
  { value: "7", text: "August" },
  { value: "8", text: "September" },
  { value: "9", text: "October" },
  { value: "10", text: "November" },
  { value: "11", text: "December" },
];

export const exampleLabels = [
  { text: "First Name", value: "firstName" },
  { text: "Last Name", value: "lastName" },
  { text: "Start Date", value: "startDate" },
  { text: "Department", value: "department" },
  { text: "Date of Birth", value: "dateOfBirth" },
  { text: "Street", value: "street" },
  { text: "City", value: "city" },
  { text: "State", value: "state" },
  { text: "Zip Code", value: "zipCode" },
];

export const exampleData = [
  {
    firstName: "John",
    lastName: "Doe",
    startDate: "04/14/2021",
    department: "Marketing",
    dateOfBirth: "01/01/1990",
    street: "Main Street",
    city: "NY",
    state: "AL",
    zipCode: "01800",
  },
  {
    firstName: "Elisa",
    lastName: "Tyrel",
    startDate: "03/02/2020",
    department: "Marketing",
    dateOfBirth: "01/25/1988",
    street: "Helia Street",
    city: "San Francisco",
    state: "AK",
    zipCode: "85699",
  },
  {
    firstName: "Roland",
    lastName: "Smith",
    startDate: "12/20/2020",
    department: "Sales",
    dateOfBirth: "01/16/1978",
    street: "Cross Street",
    city: "Irvine",
    state: "BK",
    zipCode: "78965",
  },
  {
    firstName: "Laetitia",
    lastName: "Menirel",
    startDate: "11/03/2014",
    department: "Engineering",
    dateOfBirth: "08/24/1985",
    street: "High Street",
    city: "Chicago",
    state: "UJ",
    zipCode: "87120",
  },
  {
    firstName: "Roman",
    lastName: "Pelio",
    startDate: "01/28/2018",
    department: "Human Resources",
    dateOfBirth: "05/22/1990",
    street: "Sea Street",
    city: "Seattle",
    state: "SG",
    zipCode: "99852",
  },
  {
    firstName: "Kristen",
    lastName: "Bird",
    startDate: "09/20/2012",
    department: "Marketing",
    dateOfBirth: "03/15/1975",
    street: "Side Street",
    city: "Boston",
    state: "VL",
    zipCode: "20369",
  },
  {
    firstName: "Nico",
    lastName: "Smith",
    startDate: "02/02/2017",
    department: "Legal",
    dateOfBirth: "03/29/1987",
    street: "Round Street",
    city: "Detroit",
    state: "DP",
    zipCode: "36124",
  },
  {
    firstName: "Lea",
    lastName: "Regan",
    startDate: "10/08/2015",
    department: "Engineering",
    dateOfBirth: "09/25/1979",
    street: "End Street",
    city: "Baltimore",
    state: "PI",
    zipCode: "79582",
  },
  {
    firstName: "Tim",
    lastName: "Legol",
    startDate: "02/13/2021",
    department: "Marketing",
    dateOfBirth: "10/05/1995",
    street: "Holy Street",
    city: "Dallas",
    state: "CM",
    zipCode: "25001",
  },
  {
    firstName: "Celia",
    lastName: "Hugh",
    startDate: "04/14/2021",
    department: "Marketing",
    dateOfBirth: "06/14/1992",
    street: "Low Street",
    city: "Austin",
    state: "HY",
    zipCode: "97312",
  },
];

export const days = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];
